name: promote
on:
  push:
    tags:
    - v*.*.*

jobs:
  promote-local:
    uses: CloudNativeEntrepreneur/actions/.github/workflows/gitops-promote-helm.yaml@main
    secrets: inherit
    with:
      environment_repository: CloudNativeEntrepreneur/example-local-env
      project: example-local-env
      pull_request: false

  promote-prod:
    uses: CloudNativeEntrepreneur/actions/.github/workflows/gitops-promote-helm.yaml@main
    secrets: inherit
    with:
      environment_repository: CloudNativeEntrepreneur/example-prod-env
      project: example-prod-env
      pull_request: false